### ISSUE TITLE
The introduction posts (category: people) do not have the same formatting as the posts on the home page

### ISSUE THREAD

**Issue by aleksati** [MCT-master/mct-master.github.io#33] opened 2021-08-25 12:29 UTC

**Comment by stefanofasciani** [comment] 2021-08-25 12:44
I notice that after the latest update to the blog Theme. I believe that the problem is between lines 90 and 117 of people.md . Some modification (likely minor, is needed).

**Comment by jacksongoode** [comment] 2021-08-26 01:56
Fixed in latest commit. That page didn't follow the standard blog mechanism.

**Closed as completed** 2021-08-26 01:57 UTC
Labels: help wanted, UI
